const data = {
  products: [
    {
      name: '4000lm Full HD Network Business Projector',
      slug: 'Full HD 1080p Resolution',
      category: 'Monitora/Projektora',
      image: '/images/p13.jpg', 
      price: 899,
      countInStock: 5,
      brand: 'Dell',
      rating: 4.5,
      numReviews: 2,
      description: 'USB Reader for PC-Less Presentations & Networked Presentation',
    },
    {
     
      name: 'smartphone Acer',
      slug: 'Z150',
      category: 'Telefona',
      image: '/images/p10.jpg',
      price: 250,
      countInStock: 0,
      brand: 'Acer',
      rating: 4.0,
      numReviews: 1,
      description: '32 GB RAM',
    },
    {
      name: 'Mac Book Pro 2022',
      slug: '13-inch MacBook Pro with M2',
      category: 'Laptop',
      image: '/images/p9.jpg',
      price: 2000,
      countInStock: 5,
      brand: 'Apple',
      rating: 4.5,
      numReviews: 1,
      description: 'macOS Ventura ',
    },
    {
      name: 'Smartphone Samsung',
      slug: 'Samsung Galaxy 21 Ultra',
      category: 'Telefona',
      image: '/images/p6.jpg',
      price: 980,
      countInStock: 4,
      brand: 'Samsung',
      rating: 4.5,
      numReviews: 1,
      description: '256 GB ',
    },
    {
      name: 'Smartphone',
      slug: 'Iphone 12',
      category: 'Telefona',
      image: '/images/p1.jpg',
      price: 900,
      countInStock: 2,
      brand: 'Apple',
      rating: 5,
      numReviews: 1,
      description: 'Iphone 12 Pro Max 256GB',
    },
  ],
};
export default data;
